export default function Tabela(){
    return(
        <table>
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Sobrenome</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Higor</td>
                    <td>Luiz</td>
                    <td>Higor@gmail.com</td>
                </tr>
                <tr>
                    <td>Mayara</td>
                    <td>Luiz</td>
                    <td>mayara@gmail.com</td>
                </tr>
                <tr>
                    <td>Ana</td>
                    <td>Luiz</td>
                    <td>ana@gmail.com</td>
                </tr>
            </tbody>
        </table>
    )
}